### ISSUE TITLE
Alternative download of APK

### ISSUE THREAD

**Issue by IzzySoft** [adgad/kboard#1]
Would you mind making your app available to "Google free" people? It seems to meet the inclusion criteria of [F-Droid](https://f-droid.org/), so I could help you getting it listed there. Alternatively, adding the APK to your [release tags](https://github.com/adgad/kboard/releases) would be a good start (and enabling me to add it to [my repo](https://apt.izzysoft.de/fdroid/repo) immediately).

**Comment by adgad** [comment]
Hello!

I've added the APK to releases. If you fancy helping getting it listed on F-Droid that would be _great_! Otherwise I can have a look when I get a chance :)

**Comment by IzzySoft** [comment]
Thanks a lot! Looks good so far (for testing, I've [added it to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.adgad.kboard)

For getting it into the official repo, one thing is missing: A FOSS license. Have you decided on one? Once that done, I'd file the RFP for you.

Further, a nice-to-have would be screenshots. Best if you could provide them via Fastlane/Triple-T (see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) for details). That's the sae structure Play store uses – so you'd need to set it up once and then can use it in both worlds. As said: nice-to-have, not a must-have – so take your time to consider.

Oh, and please let me know once you've chosen (and set) the license for your project, so I can start the RFP for you :innocent:

PS: What for does your keyboard need the Internet permission?

**Comment by esmoak** [comment]
@IzzySoft unless I'm mistaken, the internet permission is needed to execute the CURL commands to create http endpoints mentioned in the Readme.

Thanks for helping to move this forward for F-Droid inclusion.

**Comment by IzzySoft** [comment]
Good point, @esmoak – I missed those Curl commands!

**Comment by adgad** [comment]
I've added a License! Will take a look at fastlane/triple t later this week hopefully.

Thanks a bunch, this is super helpful 😬

**Comment by IzzySoft** [comment]
Thanks, Adgad – updated that in my repo (where it will show up with tomorrow's sync.

Let me know when I shall file an RFP for the official repo. With the license added, I could do that straight away – or wait until you've established Fastlane data, so we get that right from the start.

And glad to help!

**Comment by adgad** [comment]
Okay, so I've added the fastlane metadata, and recreated the tag/release so the metadata is included. I _think_ that's enough? Let me know if I'm missing anything 😃

**Comment by IzzySoft** [comment]
I'm not familiar with Fastlane, so I cannot tell about the structure (is it just a `metadata` directory in the top-level dir – or is that confugurable? From the past I remember a different directory name – and indeed, according to the [Fastlane docu](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#changelogs-whats-new), there's a level missing: `/fastlane/metadata/android` should be the "root" containing the "locale directories"). Text files look OK to me, but I cannot find any screenshot?

**Comment by adgad** [comment]
I think I've got everything in the right place now. Fastlane doesn't seem to like any of my screenshot sizes, so not sure they'll be accepted. Do you fancy filing an RFP anyway, and I can update screenshots later?

**Comment by IzzySoft** [comment]
Sure, that can be done. Screenshots would then be fetched with a future update.

So [here you go](https://gitlab.com/fdroid/rfp/issues/882). But please take care that your tag names match the app versions: currently v4.1.1 points to a 4.1.2. And please do not remove tags (they don't use space but are needed for reference).

**Comment by IzzySoft** [comment]
One minor issue you might wish to solve was pointed out by the F-Droid bot behind that link ("unverified gradle download"). Then, when you've fixed the tag, your app can be processed.

**Comment by IzzySoft** [comment]
Closing as it's available via the official F-Droid repo now.
