### ISSUE TITLE
command problem

### ISSUE THREAD

**Issue by vinniec** [adgad/kboard#10]
Maybe I'm wrong but I can't create the macro to insert a comma:
"/,!i(,)" does not work, it creates an "i" and slows down the keyboard.

Another problem is that in the "termux" application the commands "j" & "k" for move the cursor don't work, but I think this is not a kboard problem.

**Comment by adgad** [comment]
That's kind of a known bug where it gets into a recursive infinite loop 😬 (because , is defined as a custom key, and i will try to insert the custom key.

To do that - you don't actually need to do it as a macro. Just having a custom key with , should do the trick!
